export type Option = { value: string; label: string };

export const UNIVERSITIES: Option[] = [
  { value: "Arizona State University", label: "Arizona State University" },
  { value: "Barnard College", label: "Barnard College" },
  { value: "Cal Poly Pomona", label: "Cal Poly Pomona" },
  { value: "California Polytechnic State University", label: "Cal Poly San Luis Obispo" },
  { value: "California Institute of Technology", label: "Caltech" },
  { value: "Carnegie Mellon University", label: "Carnegie Mellon University" },
  { value: "Chapman University", label: "Chapman University" },
  { value: "Claremont McKenna College", label: "Claremont McKenna College" },
  { value: "Columbia University", label: "Columbia University" },
  { value: "Cornell University", label: "Cornell University" },
  { value: "California State University, Fullerton", label: "CSU Fullerton" },
  { value: "California State University, Long Beach", label: "CSU Long Beach" },
  { value: "California State University, Los Angeles", label: "CSU Los Angeles" },
  { value: "California State University, Northridge", label: "CSU Northridge" },
  { value: "De Anza College", label: "De Anza College" },
  { value: "Diablo Valley College", label: "Diablo Valley College" },
  { value: "Georgia Institute of Technology", label: "Georgia Tech" },
  { value: "Harvard University", label: "Harvard University" },
  { value: "Harvey Mudd College", label: "Harvey Mudd College" },
  { value: "Indiana University", label: "Indiana University" },
  { value: "Irvine Valley College", label: "Irvine Valley College" },
  { value: "Loyola Marymount University", label: "Loyola Marymount University" },
  { value: "MIT", label: "MIT" },
  { value: "National University of Singapore", label: "National University of Singapore" },
  { value: "New York University", label: "New York University (NYU)" },
  { value: "North Carolina A&T State University", label: "North Carolina A&T State University" },
  { value: "North Carolina State University", label: "North Carolina State University" },
  { value: "Occidental College", label: "Occidental College" },
  { value: "Orange Coast College", label: "Orange Coast College" },
  { value: "Oregon State University", label: "Oregon State University" },
  { value: "Pepperdine University", label: "Pepperdine University" },
  { value: "Pitzer College", label: "Pitzer College" },
  { value: "Pomona College", label: "Pomona College" },
  { value: "Princeton University", label: "Princeton University" },
  { value: "Purdue University", label: "Purdue University" },
  { value: "Rice University", label: "Rice University" },
  { value: "Rutgers University", label: "Rutgers University" },
  { value: "San Diego State University", label: "San Diego State University" },
  { value: "San Jose State University", label: "San Jose State University" },
  { value: "Santa Clara University", label: "Santa Clara University" },
  { value: "Scripps College", label: "Scripps College" },
  { value: "Smith College", label: "Smith College" },
  { value: "Stanford University", label: "Stanford University" },
  { value: "Tufts University", label: "Tufts University" },
  { value: "UC Berkeley", label: "UC Berkeley" },
  { value: "UC Davis", label: "UC Davis" },
  { value: "UC Irvine", label: "UC Irvine" },
  { value: "UC Los Angeles", label: "UC Los Angeles" },
  { value: "UC Merced", label: "UC Merced" },
  { value: "UC Riverside", label: "UC Riverside" },
  { value: "UC San Diego", label: "UC San Diego" },
  { value: "UC Santa Barbara", label: "UC Santa Barbara" },
  { value: "UC Santa Cruz", label: "UC Santa Cruz" },
  { value: "University of Arizona", label: "University of Arizona" },
  { value: "University of Illinois Urbana-Champaign", label: "University of Illinois Urbana-Champaign" },
  { value: "University of Massachusetts Amherst", label: "University of Massachusetts Amherst" },
  { value: "University of Michigan", label: "University of Michigan" },
  { value: "University of Nevada, Las Vegas", label: "University of Nevada, Las Vegas" },
  { value: "University of Nevada, Reno", label: "University of Nevada, Reno" },
  { value: "University of North Texas", label: "University of North Texas" },
  { value: "University of Oregon", label: "University of Oregon" },
  { value: "University of San Diego", label: "University of San Diego" },
  { value: "University of San Francisco", label: "University of San Francisco" },
  { value: "University of Southern California", label: "University of Southern California (USC)" },
  { value: "University of Texas at Dallas", label: "University of Texas at Dallas" },
  { value: "University of the Pacific", label: "University of the Pacific" },
  { value: "University of Washington", label: "University of Washington" },
  { value: "University of Texas at Austin", label: "UT Austin" },
  { value: "Western Governors University", label: "Western Governors University" },
  { value: "Yale University", label: "Yale University" },
  { value: "Other", label: "Other" },
];

export const MAJORS: Option[] = [
  { value: "Architecture", label: "Architecture" },
  { value: "Art", label: "Art" },
  { value: "Arts, Technology, and the Business of Innovation", label: "Arts, Technology, and the Business of Innovation" },
  { value: "Asian American Studies", label: "Asian American Studies" },
  { value: "Biochemistry and Molecular Biology", label: "Biochemistry and Molecular Biology" },
  { value: "Biological Sciences", label: "Biological Sciences" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering" },
  { value: "Business Administration", label: "Business Administration" },
  { value: "Business Economics", label: "Business Economics" },
  { value: "Business Information Management", label: "Business Information Management (BIM)" },
  { value: "Cognitive Science", label: "Cognitive Science" },
  { value: "Cognitive Science (Design & Interaction)", label: "Cognitive Science (Design & Interaction)" },
  { value: "Cognitive Science and Economics", label: "Cognitive Science and Economics" },
  { value: "Communication", label: "Communication" },
  { value: "Computer Graphics Technology", label: "Computer Graphics Technology" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Computer Science and Engineering", label: "Computer Science and Engineering" },
  { value: "Data Science", label: "Data Science" },
  { value: "Digital Media", label: "Digital Media" },
  { value: "Economics", label: "Economics" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "English", label: "English" },
  { value: "Film & Media Studies", label: "Film & Media Studies" },
  { value: "Fine Arts", label: "Fine Arts" },
  { value: "Game Design", label: "Game Design" },
  { value: "Game Design and Interactive Media", label: "Game Design and Interactive Media (GDIM)" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Human-Computer Interaction", label: "Human-Computer Interaction" },
  { value: "ICAM & Design", label: "ICAM & Design" },
  { value: "Industrial and Systems Engineering", label: "Industrial and Systems Engineering" },
  { value: "Industrial Design", label: "Industrial Design" },
  { value: "Informatics / HCI", label: "Informatics / HCI" },
  { value: "Integrated Design and Media", label: "Integrated Design and Media" },
  { value: "Interaction Design", label: "Interaction Design" },
  { value: "Interdisciplinary Art & Design Studies", label: "Interdisciplinary Art & Design Studies" },
  { value: "Marketing", label: "Marketing" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Mathematics of Computation", label: "Mathematics of Computation" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering" },
  { value: "Pharmaceutical Sciences", label: "Pharmaceutical Sciences" },
  { value: "Physics", label: "Physics" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Public Health", label: "Public Health" },
  { value: "Sociology", label: "Sociology" },
  { value: "Software Engineering", label: "Software Engineering" },
  { value: "Statistics", label: "Statistics" },
  { value: "Studio Art", label: "Studio Art" },
  { value: "Undeclared / Undecided", label: "Undeclared / Undecided" },
  { value: "UX/UI Design", label: "UX/UI Design" },
  { value: "Visual Communication Design", label: "Visual Communication Design" },
  { value: "Other", label: "Other" },
];